version: "3.8"
name: jekyll-site

services:
  jekyll:
    image: jekyll-site
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0 --watch
